//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace AtelierLaDiDa.DataBases.JP
{
	/// <summary>
	/// Database       : atelierLaDiDaA17JPSqlite
	/// Data Source    : atelierLaDiDaA17JPSqlite
	/// Server Version : 3.24.0
	/// </summary>
	public partial class AtelierLaDiDaA17JPSqliteDB : LinqToDB.Data.DataConnection
	{
		public ITable<Sophie> Sophie { get { return this.GetTable<Sophie>(); } }

		public AtelierLaDiDaA17JPSqliteDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AtelierLaDiDaA17JPSqliteDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("Sophie$")]
	public partial class Sophie
	{
		[Column("No#"), Nullable] public double? No         { get; set; } // real
		[Column(),      Nullable] public string  Name       { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Attribute1 { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Attribute2 { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Attribute3 { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Attribute4 { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Attribute5 { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Type1      { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Type2      { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Type3      { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Type4      { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Source1    { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Source2    { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Source3    { get; set; } // varchar(255)
		[Column(),      Nullable] public string  Source4    { get; set; } // varchar(255)
		[Column(),      Nullable] public char?   TRIAL973   { get; set; } // char(1)
	}
}

#pragma warning restore 1591
