//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace AtelierLaDiDa.DataBases
{
	/// <summary>
	/// Database       : atelierLaDiDaA11Sqlite
	/// Data Source    : atelierLaDiDaA11Sqlite
	/// Server Version : 3.24.0
	/// </summary>
	public partial class AtelierLaDiDaA11SqliteDB : LinqToDB.Data.DataConnection
	{
		public ITable<Rorona> Rorona { get { return this.GetTable<Rorona>(); } }

		public AtelierLaDiDaA11SqliteDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AtelierLaDiDaA11SqliteDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("Rorona$")]
	public partial class Rorona
	{
		[Column("No#"), Nullable] public string No         { get; set; } // varchar(255)
		[Column(),      Nullable] public string Name       { get; set; } // varchar(255)
		[Column(),      Nullable] public string Attribute1 { get; set; } // varchar(255)
		[Column(),      Nullable] public string Attribute2 { get; set; } // varchar(255)
		[Column(),      Nullable] public string Attribute3 { get; set; } // varchar(255)
		[Column(),      Nullable] public string Attribute4 { get; set; } // varchar(255)
		[Column(),      Nullable] public string Type1      { get; set; } // varchar(255)
		[Column(),      Nullable] public string Type2      { get; set; } // varchar(255)
		[Column(),      Nullable] public string Type3      { get; set; } // varchar(255)
		[Column(),      Nullable] public string Type4      { get; set; } // varchar(255)
		[Column(),      Nullable] public string Type5      { get; set; } // varchar(255)
		[Column(),      Nullable] public string Type6      { get; set; } // varchar(255)
		[Column(),      Nullable] public string Source1    { get; set; } // varchar(255)
		[Column(),      Nullable] public string Source2    { get; set; } // varchar(255)
		[Column(),      Nullable] public string Source3    { get; set; } // varchar(255)
		[Column(),      Nullable] public string Source4    { get; set; } // varchar(255)
		[Column(),      Nullable] public string Japanese   { get; set; } // varchar(255)
		[Column(),      Nullable] public char?  TRIAL255   { get; set; } // char(1)
	}
}

#pragma warning restore 1591
