// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace AtelierLaDiDaDatabase.Models
{
    public partial class Rorona : IAtelier
    {
        public double No { get; set; }
        public string Name { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public string Type1 { get; set; }
        public string Type2 { get; set; }
        public string Type3 { get; set; }
        public string Type4 { get; set; }
        public string Type5 { get; set; }
        public string Type6 { get; set; }
        public string Source1 { get; set; }
        public string Source2 { get; set; }
        public string Source3 { get; set; }
        public string Source4 { get; set; }
        public string Japanese { get; set; }
    }
}